services:
  students-service:
    build:
      students-service
    hostname: students-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb1

  mongodb1:
    image: mongo
    container_name: mongo_db1
    ports:
      - "27017:27017"

    environment:
     - MONGO_INITDB_ROOT_USERNAME=user
     - MONGO_INITDB_ROOT_PASSWORD=pwd

  mongo-express1:
    image: mongo-express
    container_name: mongo-express1
    restart: always
    ports:
      - "8091:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pwd
      - ME_CONFIG_MONGODB_SERVER=mongodb1
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongodb1




